#!/bin/bash
EXTRA_ARGS=()
if [ -f "$SNAP_USER_DATA/openchrom.ini" ]; then
    # Allow the user to override the openchrom.ini with their own version
    EXTRA_ARGS+=("--launcher.ini" "$SNAP_USER_DATA/openchrom.ini")
else
    echo "To override openchrom.ini, copy the default file to '$SNAP_USER_DATA/openchrom.ini' and modify to suit."
fi
GDK_BACKEND=x11
exec "$SNAP/openchrom" -configuration "${SNAP_USER_DATA}/${SNAP_ARCH}/configuration" "${EXTRA_ARGS[@]}" "$@"
