name: openchrom
base: core22

version: '1.5.0.20240216'
summary: Visualization and Analysis of mass spectrometric and chromatographic data.
description:
  OpenChrom® is an Open Source tool for the analysis and visualization of
  mass spectrometric and chromatographic data developed by Lablicate GmbH.

grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  openchrom:
    extensions: [gnome]
    command: bin/openchrom-wrapper
    plugs:
      - browser-support
      - home
      - mount-observe
      - network
      - network-bind
      - removable-media
      - x11

parts:
  openchrom:
    plugin: dump
    source: https://products.lablicate.com/openchrom/1.5.0/openchrom-lablicate_linux.x86_64_1.5.0.tar.gz
    override-build: |
      snapcraftctl build
      sed -i 's;@user.home/;@user.home/snap/openchrom/current/;' $SNAPCRAFT_PART_INSTALL/openchrom.ini
    build-packages:
      - execstack
    stage-packages:
      - libgtk-3-0
    override-prime: |
      craftctl default
      execstack -c $SNAPCRAFT_PART_INSTALL/plugins/com.sun.jna_*/com/sun/jna/freebsd-*/libjnidispatch.so
  wrappers:
    plugin: dump
    source: snap/local/wrappers
    organize:
      openchrom: bin/openchrom-wrapper
