name: openchrom
base: core22
version: 1.5.0.20241018
summary: Visualization and Analysis of mass spectrometric and chromatographic data.
description: OpenChrom® is an Open Source tool for the analysis and visualization of mass spectrometric and chromatographic data developed by Lablicate GmbH.
grade: stable
confinement: strict
architectures:
- build-on: amd64
- build-on: arm64
apps:
  openchrom:
    extensions:
    - gnome
    command: bin/openchrom-wrapper
    plugs:
    - browser-support
    - home
    - mount-observe
    - network
    - network-bind
    - removable-media
    - x11
    - dot-eclipse-org-eclipse-swtchart-extensions
    - dot-openchrom
parts:
  openchrom:
    plugin: dump
    source:
    - on amd64: https://products.lablicate.com/openchrom/1.5.0/openchrom-lablicate_linux.x86_64_1.5.0.tar.gz
    - on arm64: https://products.lablicate.com/openchrom/1.5.0/openchrom-lablicate_linux.aarch64_1.5.0.tar.gz
    override-build: |
      craftctl default
      sed -i 's;@user.home/;@user.home/snap/openchrom/current/;' $SNAPCRAFT_PART_INSTALL/openchrom.ini
    stage-packages:
    - libgtk-3-0
    - libusb-1.0-0
    - libwebkit2gtk-4.1-0
    override-prime: |
      craftctl default
      rm -r $SNAPCRAFT_PRIME/plugins/com.sun.jna_*v*/com/sun/jna/aix*/
      rm -r $SNAPCRAFT_PRIME/plugins/com.sun.jna_*v*/com/sun/jna/darwin*/
      rm -r $SNAPCRAFT_PRIME/plugins/com.sun.jna_*v*/com/sun/jna/freebsd*/
      rm -r $SNAPCRAFT_PRIME/plugins/com.sun.jna_*v*/com/sun/jna/openbsd*/
      rm -r $SNAPCRAFT_PRIME/plugins/com.sun.jna_*v*/com/sun/jna/sunos*/
      rm -r $SNAPCRAFT_PRIME/plugins/com.sun.jna_*v*/com/sun/jna/win32*/
  wrappers:
    plugin: dump
    source: snap/local/wrappers
    organize:
      openchrom: bin/openchrom-wrapper
plugs:
  dot-eclipse-org-eclipse-swtchart-extensions:
    interface: personal-files
    write:
    - $HOME/.eclipse/org.eclipse.swtchart.extensions
  dot-openchrom:
    interface: personal-files
    write:
    - $HOME/.openchrom
lint:
  ignore:
  - library:
    - plugins/**/*.so
    - features/*/jre/*/lib/*.so
    - usr/lib/**/*.so*
